# Site
title:              Rozzi Media Group
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "A boutique media and consulting firm based out of southern New Jersey. Our web properties serve the public with up-to-date news & authoritative information on New Jersey government. We also provide creative, client-centered solutions including technology and media consulting, copy editing, website design."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rozzi.media" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Forked River, NJ
phone:              (732)-504-3636
email:              hello@rozzi.media

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://rozzi.media

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
